# Generated by Django 5.2.10 on 2026-02-04 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_datetime', models.DateTimeField(help_text='When the SMS should be sent')),
                ('message', models.TextField(help_text='SMS message content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('api_response', models.TextField(blank=True, help_text='Response from SMS API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminders', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'SMS Appointment Reminder',
                'verbose_name_plural': 'SMS Appointment Reminders',
                'ordering': ['reminder_datetime'],
            },
        ),
    ]
